version: '3'
services:
  app-py:
    build: '.'
    container_name: "app-py"
    networks: 
      - api_network
    ports:
      - "88:80"
    restart: always      
    volumes:
      - ./app/:/app
    environment:
      - "TZ=Asia/Bangkok"
      - FLASK_APP=main.py
      - FLASK_DEBUG=1
      - 'RUN=flask run --host=0.0.0.0 --port=80'
    command: flask run --host=0.0.0.0 --port=80
networks: 
  api_network:
    driver: bridge